version: 2
updates:

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(gha)"
      include: scope
    labels:
      - dependencies

  # NPM
  - package-ecosystem: npm
    directory: /acme
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(acme)"
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(e2e)"
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(frontend)"
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /ratesjob
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ratesjob)"
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(server)"
    labels:
      - dependencies

  # Docker
  - package-ecosystem: docker
    directory: /acme
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /ratesjob
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
