apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: migrations
  name: migrations
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: migrations
  name: migrations
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 600
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: migrations
    spec:
      containers:
        - image: ghcr.io/arikkfir/greenstar/migrations
          env:
            - name: NEO4J_ADDRESS
              value: "neo4j://greenstar-neo4j"
          name: migrations
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
      enableServiceLinks: false
      restartPolicy: OnFailure
      serviceAccountName: migrations
  ttlSecondsAfterFinished: 1200
