name: Setup feature branch
on:
  push:
    branches-ignore:
      - main

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  create-pr:
    name: Create PR
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |-
          PR_EXISTS="$(gh pr list --base main --head ${{ github.ref_name }} --state open --json number --jq '. | length > 0')"
          if [[ "${PR_EXISTS}" == "false" ]]; then
            gh pr create --base main --head ${{ github.ref_name }} --fill --label "auto-created"
            #gh pr merge --auto --merge --delete-branch
          fi
        env:
          GH_TOKEN: ${{ secrets.ARIKKFIR_GHA_AUTOMATION }}
